$schema: http://json-schema.org/draft-07/schema#

container:
    work_dir: "/app"
    docker_file_path: "./dockerfile"

core_api:
    model: "openai/gpt-4o"
    fallback_models:
        - "openai/gpt-4o"
        - "openai/gpt-3.5-turbo"

git:
    user_email: "AiTestGen@users.noreply.github.com"
    user_name: "Ai-TestGen[bot]"

reporter:
    name: "jest"
    command: "npm run test:coverage"
    output_path: "/app/coverage_reports/testResults.json"
    report_directory: "/app/coverage_reports"

test_generation:
    iterations: 1
    limit: 1
    save_next_to_code_under_test: false
    test_directory: "tests"
    test_suffix: "test"
