$schema: http://json-schema.org/draft-07/schema#

container:
    work_dir: "/app"
    docker_file_path: "./dockerfile"

core_api:
    model: "openai/gpt-4o"
    fallback_models:
        - "openai/gpt-4o"
        - "openai/gpt-3.5-turbo"

git:
    user_email: "AiTestGen@users.noreply.github.com"
    user_name: "Ai-TestGen[bot]"

reporter:
    name: "jest"
    command: "npm run test:coverage"
    output_file_path: "/app/coverage_reports/testResults.json"
    report_directory: "/app/coverage_reports"

test_generation:
    limit: 1
    save_next_to_code_under_test: false
    test_directory: "tests"
    test_suffix: "test"

concurrency:
    batch_size: 5
    max_concurrent: 5
    embedding_batch_size: 10

indexing:
    max_semantic_chunk_lines: 200
    chunk_size: 50
    max_file_size: 1_000_000
    embedding_model: "openai/text-embedding-3-small"
    file_extensions: ["py", "js", "ts", "java", "c", "cpp", "go", "rs"]
    max_files: 50
    skip_indexing: false